import type { Metadata } from "next"
import "./globals.css"
import React, {Fragment} from "react"
import {Providers} from "@/app/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
      <Fragment>
        <Providers>
            {children}
        </Providers>
      </Fragment>
      </body>
    </html>
  )
}
